### ISSUE TITLE
Escrever resumo sobre Operadores

### ISSUE THREAD

**Issue by eduardolfalcao** [wagnersistemalima/p2-Unifacisa#1]

**Comment by wagnersistemalima** [comment]
## Operadores aritméticos

Descrição|Operador|Significado
---|---|---
1| + | Adição
2| -| Subtração
3| * | Multiplicação
4| / | Divisão
5| % | resto da divisão("mod")

## Precedência: 
1º lugar: * / %
2º lugar: + -

## Operadores comparativos

 Descrição| Operador | Significado
 |---|---|---
1| > | maior
2| < | menor
3| >= | maior ou igual
4| <= | menor ou igual
5| == | igual
6| != | diferente

## Operadores lógicos

Descrição| Operador| Significado
|---|---|---
1| && | E
2| II | OU  
3| ! | DIFERENTE

## Operadores de atribuição cumulativa

Descrição| Operador| Significado
|---|---|---
1| a += b;|a = a + b;
2| a -= b;|a = a - b;
3| a *= b;|a = a * b;  
4| a /= b; | a = a / b;
5| a %= b; | a = a % b;
