### ISSUE TITLE
Escrever resumo sobre como receber dados do teclado (Scanner)

### ISSUE THREAD

**Issue by eduardolfalcao** [wagnersistemalima/p2-Unifacisa#4]

**Comment by wagnersistemalima** [comment]
## Scanner
* Para fazer entrada de dados, criamos um objeto do tipo "Scanner"
* Scanner sc = new Scanner(System.in);
* quando não precisar mais do objeto sc criado,  fechamos o Scanner. -----> sc.close();
* Para ler uma palavra (texto sem espaços) suponhamos uma variável do tipo String declarada/ String x;
* x = sc.next();
* Para ler palavras com espaço, tipo nome: Jose Silva
* x = sc.nextLine();
* Para ler um número inteiro, suponhamos uma variável do tipo int declarada/  int x;
* x = sc.nextInt();
* Para ler um número com ponto flutuante: Observação--> Para considerar o separador de decimais como ponto, ANTES da declaração do Scanner, faça:
* Locale.setDefault(Locale.US);
* suponhamos uma variavel do tipo double declarada / double x;
* x = sc.nextDouble();
* Para ler um caractere, suponhamos uma variável do tipo char declarada: char x;
* x = sc.next().charAt(0);
