### ISSUE TITLE
Solucionar exercícios sobre Classes e Objetos (https://github.com/eduardolfalcao/P2-Unifacisa/blob/master/exercicios/ClassesEObjetos.md)

### ISSUE THREAD

**Issue by eduardolfalcao** [wagnersistemalima/p2-Unifacisa#6]

**Comment by wagnersistemalima** [comment]
[Exercicio1Carros](https://github.com/wagnersistemalima/p2-Unifacisa/tree/master/exercicio1Carro/src) :red_car: :blue_car:

[Exercicio2ClassificadoImoveis](https://github.com/wagnersistemalima/p2-Unifacisa/tree/master/exercicio2Imovel/src) :houses: :hotel:
